/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.practicafinalcoches.app;
import es.medac.practicafinalcoches.bd.ConsultasVehiculos;

/**
 * Esta clase es una interfaz grafica que nos permite usar los metodos de la clase ConsultasVehiculo
 * @author Gabriel
 */
public class MenuVehiculo extends javax.swing.JFrame {
    ConsultasVehiculos consulta = new ConsultasVehiculos();
    /**
     * Creates new form MenuVehiculo
     */
    public MenuVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        matriculaInsert = new javax.swing.JTextField();
        marcaInsert = new javax.swing.JTextField();
        modeloInsert = new javax.swing.JTextField();
        anioInsert = new javax.swing.JTextField();
        colorInsert = new javax.swing.JTextField();
        idVehInsert = new javax.swing.JTextField();
        insertBoton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        matriculaBuscar = new javax.swing.JTextField();
        buscarXMatricula = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        marcaBuscarMaMo = new javax.swing.JTextField();
        modeloBuscarMaMo = new javax.swing.JTextField();
        buscarMaMo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        marcaBuscarMaMoAn = new javax.swing.JTextField();
        modeloBuscarMaMoAn = new javax.swing.JTextField();
        buscarMaMo1 = new javax.swing.JButton();
        anioBuscarMaMoAn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        idBorrar = new javax.swing.JTextField();
        borrarVeh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        campoCambio = new javax.swing.JTextField();
        modificarVeh = new javax.swing.JButton();
        valorMod = new javax.swing.JTextField();
        condicion = new javax.swing.JTextField();
        menuPrin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("VEHICULO");

        jLabel2.setText("INSERTAR");

        matriculaInsert.setText("Matricula");

        marcaInsert.setText("Marca");

        modeloInsert.setText("Modelo");

        anioInsert.setText("Anio");

        colorInsert.setText("Color");

        idVehInsert.setText("idVehiculo");

        insertBoton.setBackground(new java.awt.Color(153, 153, 255));
        insertBoton.setText("Insertar");
        insertBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBotonActionPerformed(evt);
            }
        });

        jLabel3.setText("BUSCAR POR MATRICULA");

        matriculaBuscar.setText("Matricula");

        buscarXMatricula.setBackground(new java.awt.Color(153, 153, 255));
        buscarXMatricula.setText("Buscar");
        buscarXMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarXMatriculaActionPerformed(evt);
            }
        });

        jLabel4.setText("BUSCAR POR MARCA Y MODELO");

        marcaBuscarMaMo.setText("Marca");

        modeloBuscarMaMo.setText("Modelo");

        buscarMaMo.setBackground(new java.awt.Color(153, 153, 255));
        buscarMaMo.setText("Buscar");
        buscarMaMo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMaMoActionPerformed(evt);
            }
        });

        jLabel5.setText("BUSCAR POR MARCA , MODELO Y AÑO");

        marcaBuscarMaMoAn.setText("Marca");

        modeloBuscarMaMoAn.setText("Modelo");

        buscarMaMo1.setBackground(new java.awt.Color(153, 153, 255));
        buscarMaMo1.setText("Buscar");
        buscarMaMo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMaMo1ActionPerformed(evt);
            }
        });

        anioBuscarMaMoAn.setText("Año");
        anioBuscarMaMoAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioBuscarMaMoAnActionPerformed(evt);
            }
        });

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        jLabel6.setText("BORRAR POR ID");

        idBorrar.setText("ID");

        borrarVeh.setBackground(new java.awt.Color(153, 153, 255));
        borrarVeh.setText("Borrar");
        borrarVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarVehActionPerformed(evt);
            }
        });

        jLabel7.setText("MODIFICAR ");

        campoCambio.setText("campoCambio");

        modificarVeh.setBackground(new java.awt.Color(153, 153, 255));
        modificarVeh.setText("Modificar");
        modificarVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarVehActionPerformed(evt);
            }
        });

        valorMod.setText("valorMod");

        condicion.setText("Condicion");

        menuPrin.setBackground(new java.awt.Color(255, 51, 51));
        menuPrin.setText("Menu Principal");
        menuPrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(239, 239, 239))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuPrin)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(campoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(valorMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(condicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(modificarVeh))
                        .addComponent(jLabel7)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(idBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(borrarVeh))
                        .addComponent(jLabel6)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(marcaBuscarMaMoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(modeloBuscarMaMoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(anioBuscarMaMoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(buscarMaMo1))
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(marcaBuscarMaMo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(modeloBuscarMaMo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(buscarMaMo))
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(matriculaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(buscarXMatricula))
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(matriculaInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(marcaInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(modeloInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(anioInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(colorInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(idVehInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(insertBoton))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matriculaInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idVehInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertBoton))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matriculaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarXMatricula))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaBuscarMaMo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloBuscarMaMo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarMaMo))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaBuscarMaMoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloBuscarMaMoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anioBuscarMaMoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarMaMo1))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarVeh))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarVeh)
                    .addComponent(valorMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(condicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPrin)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anioBuscarMaMoAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioBuscarMaMoAnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioBuscarMaMoAnActionPerformed

    private void insertBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBotonActionPerformed
        resultado.setText(consulta.InsertarVehiculos(Integer.parseInt(idVehInsert.getText()), matriculaInsert.getText(), marcaInsert.getText(), 
                    modeloInsert.getText(), anioInsert.getText(), colorInsert.getText()));
    }//GEN-LAST:event_insertBotonActionPerformed

    private void buscarXMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarXMatriculaActionPerformed
        resultado.setText(consulta.BuscarVehiculoxMatri(matriculaBuscar.getText()));
    }//GEN-LAST:event_buscarXMatriculaActionPerformed

    private void buscarMaMoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMaMoActionPerformed
        resultado.setText(consulta.BuscarVehiculoxmarYmod(marcaBuscarMaMo.getText(), modeloBuscarMaMo.getText()));
    }//GEN-LAST:event_buscarMaMoActionPerformed

    private void buscarMaMo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMaMo1ActionPerformed
        resultado.setText(consulta.BuscarMaMoAn(marcaBuscarMaMoAn.getText(), modeloBuscarMaMoAn.getText(), anioBuscarMaMoAn.getText()));
    }//GEN-LAST:event_buscarMaMo1ActionPerformed

    private void borrarVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarVehActionPerformed
        resultado.setText(consulta.EliminarVehiculo(Integer.parseInt(idBorrar.getText())));
    }//GEN-LAST:event_borrarVehActionPerformed

    private void modificarVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarVehActionPerformed
        resultado.setText(consulta.ModificarVeh(campoCambio.getText(), valorMod.getText(), condicion.getText()));
    }//GEN-LAST:event_modificarVehActionPerformed

    private void menuPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrinActionPerformed
        MenuPrincipal principal = new MenuPrincipal();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPrinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anioBuscarMaMoAn;
    private javax.swing.JTextField anioInsert;
    private javax.swing.JButton borrarVeh;
    private javax.swing.JButton buscarMaMo;
    private javax.swing.JButton buscarMaMo1;
    private javax.swing.JButton buscarXMatricula;
    private javax.swing.JTextField campoCambio;
    private javax.swing.JTextField colorInsert;
    private javax.swing.JTextField condicion;
    private javax.swing.JTextField idBorrar;
    private javax.swing.JTextField idVehInsert;
    private javax.swing.JButton insertBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marcaBuscarMaMo;
    private javax.swing.JTextField marcaBuscarMaMoAn;
    private javax.swing.JTextField marcaInsert;
    private javax.swing.JTextField matriculaBuscar;
    private javax.swing.JTextField matriculaInsert;
    private javax.swing.JButton menuPrin;
    private javax.swing.JTextField modeloBuscarMaMo;
    private javax.swing.JTextField modeloBuscarMaMoAn;
    private javax.swing.JTextField modeloInsert;
    private javax.swing.JButton modificarVeh;
    private javax.swing.JTextArea resultado;
    private javax.swing.JTextField valorMod;
    // End of variables declaration//GEN-END:variables
}
